title: Maryland League System Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.marylandleague.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2 UTC
  down: "#e60000"
  systems:
    - name: API
      category: Uncategorized
    - name: Website
      category: Uncategorized
    - name: CloudFlare
      category: Third Party
    - name: Mail Server
      category: Third Party
    - name: Payments
      category: Third Party
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/ml-status.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
      closed: true
    - name: Third Party
      closed: false
  description: We continuously monitor the status of our services. In the event of
    any interruptions, updates and relevant information will be promptly posted
    here.
  enableCustomHTML: false
  useLargeHeaderDesign: false
